#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Python Interface to The Sanskrit Heritage Site

Use The Sanskrit Heritage Platform using,

* Web mirror
  - no installation required
  - makes HTTP requests
* Local installation
  - faster
  - uses console
  - no HTTP requests required

Using Local Installation
------------------------
- Heritage_Platform/ML/ contains the scripts
- export QUERY_STRING as shell variable
  (referred to as OPTION_STRING in this code alongwith the '&text=TEXT' part)
- execute various scripts, such as ./reader
- still produces HTML output that needs to be parsed

# Default input needs to be in the devanagari format
# utils.devanagari_to_velthuis() function will convert this to VH
"""

###############################################################################

import os
import io
import sys
import re
import time
import random
import signal
import logging
import functools

# import subprocess
import urllib.parse
from dataclasses import dataclass, field

import sh

import requests
import bs4

from .constants import HERITAGE_COLOURS
from .utils import build_query_string, devanagari_to_velthuis

###############################################################################
# TODO: Do we need to use python-frozendict (PyPI)?


class frozendict(dict):
    def __hash__(self):
        return hash(frozenset(self.items()))


def freezeargs(func):
    """
    Transform mutable dictionnary arguments into immutable frozen ones

    Useful to be compatible with @cache. Should be added on top of @cache
    """

    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        args = tuple(
            [frozendict(arg) if isinstance(arg, dict) else arg for arg in args]
        )
        kwargs = {
            k: frozendict(v) if isinstance(v, dict) else v for k, v in kwargs.items()
        }
        return func(*args, **kwargs)

    for method in ["cache_info", "cache_clear"]:
        if callable(getattr(func, method, None)):
            setattr(wrapper, method, getattr(func, method))

    return wrapper


###############################################################################


def timeout_handler(signum, frame):
    raise TimeoutError("Time limit exceeded.")


if hasattr(signal, "SIGALRM"):
    signal.signal(signal.SIGALRM, timeout_handler)
    alarm = signal.alarm
else:

    def alarm(x):
        return x


###############################################################################


@dataclass
class HeritageAnalysis:
    case: str = field(default=None)
    number: str = field(default=None)
    gender: str = field(default=None)
    tense: str = field(default=None)


@dataclass
class Token:
    pass


###############################################################################


class TreeScopedCache:
    """
    Caches lexicon lookups for the lifetime of a single parse tree.

    lets instances of this class get garbage collected
    """

    def __init__(self, heritage):
        self.h = heritage
        self.cache = {}

    def get_lexicon_entry(self, lexicon_id, entry_id, variant=None):
        """
        Checks cache before fetching lexicon entry.
        """
        cache_key = (lexicon_id, entry_id, variant)

        if cache_key in self.cache:
            return self.cache[cache_key]  # Return cached result

        # Fetch fresh data
        result = self.h.get_lexicon_entry(lexicon_id, entry_id, variant)

        result["lexicon_entry"] = cache_key if variant else (lexicon_id, entry_id)

        # Store only for this tree instance
        self.cache[cache_key] = result
        return result


class HeritageOutput:
    """
    Heritage Output Parser

    Parse output generated by various utilities from Heritage Platform
    """

    CLASSES = {"footer": ["enpied"]}

    def __init__(self, html: str):
        self.logger = logging.getLogger(__name__)
        self.html = html
        self.soup = bs4.BeautifulSoup(html, "html.parser")
        self.process()

    def process(self, html: str = None):
        """Process the html and extract basic information"""
        # Allow re-using of the class
        if html is not None:
            self.html = html
            self.soup = bs4.BeautifulSoup(html, "html.parser")

        self.body = self.soup.find("body")
        self.footer = self.body.find("div", class_=self.CLASSES["footer"])

        # Extract Meta Information
        self.meta = {}
        for meta in self.soup.find_all("meta"):
            if meta.get("name", ""):
                self.meta[meta.get("name")] = meta.get("content", "")
            if meta.get("property", ""):
                self.meta[meta.get("property")] = meta.get("content", "")

        # Extract Title
        self.title = self.soup.find("title")
        self.inner_title = self.body.find("h1", class_="title")

        # Find Relevant Body Children
        self.blocks = self.body.find_all()

    def find_root_analysis(self, analysis):
        analyses = []

        # print("you want analysis?", analysis)
        def append_if_not_already(obj):
            has_item_already = False
            for x in analyses:
                has_item_already = (
                    x["root"] == obj["root"] and x["anchor_href"] == obj["anchor_href"]
                )
                if has_item_already:
                    break
            if not has_item_already:
                analyses.append(obj)

        parts = str(analysis).split("<br/>")
        for part in parts:
            # el = part
            head = None
            tail = None
            (head, tail) = part.split("]{")
            head = head[1:]
            tail = tail[:-1]

            # print("h:", head)
            # print("t:", tail)

            soup = bs4.BeautifulSoup(head, "html.parser")
            anchor = soup.find("a")

            if anchor is None:
                # print("interesting anchor?", soup, anchor)
                # soupstr = str(soup)
                # head = soupstr.split("]")[0][1:]
                # tail = soupstr.split("{")[-1][:-1]
                obj = {
                    "root": head,
                    "analyses": tail.split(" "),
                    "anchor_href": "",
                }
                append_if_not_already(obj)
                continue

            # anchor_txt = anchor.get_text().split("_")[0]
            anchor_href = anchor.get("href")
            # extract lexicon
            # anchor.decompose()
            root_txt = tail

            if "{" in head:
                head_root = head.split("{")[1].split("}")[0]
                root_txt = f"{head_root} | {root_txt}"

            # print("rooty", root_txt)
            roots = []
            root_chunks = root_txt.split("|")
            # print("part", anchor_txt, root_txt)
            term_analyses = []
            for chunk in root_chunks:
                chunk_sub = chunk
                if "." in chunk:  # must be roma
                    chunk_sub = re.sub(r"[\[\]\.0-9]", "", chunk).strip()
                chunk_sub = re.sub(r" +", " ", chunk_sub).split(" ")
                chunk_parts = []
                for s in chunk_sub:
                    if s:
                        chunk_parts.append(s)
                # print("turned", chunk, chunk_parts)
                # chunk.replace(r'', )
                term_analyses.append(chunk_parts)
            lexicon_sections = anchor_href.split("/")[-1].split("#")
            # lexicon = (lexicon_sections[0], lexicon_sections[1])
            lexicon = tuple(lexicon_sections)
            obj = dict(
                root=soup.get_text().split(" ")[0],
                anchor_href=anchor_href,
                lexicon=lexicon,
                # lexicon_section=lexicon_sections,
                # href=anchor_href,
                analyses=term_analyses,
            )
            append_if_not_already(obj)
            # else:
            #     print("skipping I think a dupe")
            # print("part", "[<a"+ part)
        # print(analyses)
        return analyses

    def extract_segmenter_output(self, meta: bool = False):
        soup = bs4.BeautifulSoup(self.html, "html.parser")
        solution = {}
        # solution["id"] = 0
        words = []
        solution["words"] = words

        tables = soup.find_all("table")
        terms = {}
        categories = {}
        for table in tables:
            table_txt = table.get_text().strip()
            if "Chunks" in table_txt:
                continue
            if "Solutions" in table_txt:
                continue
            if "Grammar" in table_txt:
                continue
            if table_txt == "":
                # print("skipping empty", table)
                continue
            if " " in table_txt:
                # print("contains spaces.. probably should skip")
                continue
            t_class = table.get("class")
            # if table.get("class"):
            # if table["classes"]:
            #     print("wow classes")
            if t_class:
                # print("amazing a tclass", t_class)
                if t_class == ["center"]:
                    # print("no use in messing with this...")
                    continue
            # print("checking", table_txt.strip())
            # print("wow table", table)
            soup = table
            # TODO: pretty brittle start/end
            thingy = bs4.BeautifulSoup(
                soup.find("td").get("onclick")[9:-63], "html.parser"
            )
            # print("wow thing", thingy.get_text())
            datum = terms.get(table_txt, {})
            entries = datum.get("entries", [])
            categories = datum.get("categories", [])
            entries.append(thingy)
            categories.append(t_class)
            # TODO: if term is repeated table_txt wipes out entries...
            # test output on the mahamantra example
            terms[table_txt] = dict(
                entries=entries,
                categories=categories,
            )

        words = []
        for term, datum in terms.items():
            # print("welcome to term", term)
            entries = datum.get("entries")
            categories = datum.get("categories")
            # print(term, entries, categories[term])
            # css_classes = categories[term]
            word_forms = []

            def add_if_not_already(word_analysis):
                has_item_already = False
                for x in word_forms:
                    has_item_already = (
                        # TODO: check analyses line
                        x["category"] == word_analysis["category"]
                        and x["root"] == word_analysis["root"]
                        and x["anchor_href"] == word_analysis["anchor_href"]
                    )
                    if has_item_already:
                        # print("comparing!", x)
                        # print("compared!", word_analysis)
                        # print("skipping other dupe")
                        break
                if not has_item_already:
                    word_forms.append(word_analysis)

            word = dict(
                text=term,
            )
            for n in range(len(entries)):
                analysis = entries[n]
                css_classes = categories[n]
                word_entry = word.copy()
                word_entry["category"] = [
                    HERITAGE_COLOURS.get(css_class.split("_back")[0], None)
                    for css_class in css_classes
                ]
                if len(word_entry["category"]) == 1:
                    word_entry["category"] = word_entry["category"][0]
                # word_entry["soup"] = analysis
                for analysis in self.find_root_analysis(analysis):
                    word_analysis = word_entry.copy()
                    word_analysis.update(analysis)
                    add_if_not_already(word_analysis)
                # word_copy.update(analysis)
            for word in word_forms:
                del word["anchor_href"]
            words.append(word_forms)

            # words.append(dict(
            #     text=term,
            #     category = [ ],
            # ))

        solution["id"] = 0
        solution["words"] = words

        return {"0": solution}
        # return self.extract_reader_inner(self.html, meta)

    def extract_reader_inner(self, block, meta: bool = False):
        if "Solution" not in block:
            # print("MYSTERYBEGIN")
            # print(block)
            # print("MYSTERYEND")
            return ("nothing", None)
            # raise ValueError("What is this block?")

        solution = {}

        soup = bs4.BeautifulSoup(block, "html.parser")
        solution_id = None
        first_span = soup.find("span")
        solution_id = int(first_span.text.split()[1])

        solution["id"] = solution_id
        solution["words"] = []

        if meta:
            parser_url = first_span.find("a")["href"]
            # TODO: Better parsing of options
            parser_options = dict(
                [e.split("=") for e in re.split(r"&amp;|&|;", parser_url.split("?")[1])]
            )
            solution["parser_options"] = parser_options

        tables = soup.find_all("table")
        for table in tables:
            if table.find("table"):
                word = {}
                word["text"] = table.previous_sibling.get_text()
            else:
                # Inner table contains analysis and it occurs after
                # the original word
                table_txt = table.get_text()
                self.logger.debug(table_txt)
                analyses = self.parse_reader_analysis(table)
                self.logger.debug(analyses)
                css_classes = table.get("class", [])
                if meta:
                    word["classes"] = css_classes
                word["category"] = [
                    HERITAGE_COLOURS.get(css_class.split("_back")[0], None)
                    for css_class in css_classes
                ]
                word_analyses = []
                for analysis in analyses:
                    # word_copy = word.copy()
                    # print(word)
                    word_copy = {
                        "text": word["text"],
                        "category": word["category"],
                        # "variant": analysis,
                    }
                    word_copy.update(analysis)
                    word_analyses.append(word_copy)
                solution["words"].append(word_analyses)

        return solution_id, solution

    def extract_reader_output(self, meta: bool = False):
        hr_blocks = self.html.split("<hr>")
        if len(hr_blocks) < 2:
            # print(self.html)
            self.logger.error("No solutions found.")
            return None

        solutions = {}
        for block in hr_blocks[2:]:
            (solution_id, solution) = self.extract_reader_inner(block)
            if solution is not None:
                solutions[solution_id] = solution
        return solutions

    def extract_analysis(self, meta: bool = False):
        """
        Extract analysis from HTML

        Parameters
        ----------
        meta : bool
            If True, include meta information, i.e, parse options, classes
            The default is False.
        """
        if self.title.text == "Sanskrit Reader Companion":
            # print(self.soup)
            return self.extract_reader_output(meta)
        elif self.title.text == "Sanskrit Segmenter Summary":
            return self.extract_segmenter_output(meta)
        else:
            self.logger.error(f"Invalid output page: {self.title.text}")
            return None

    def extract_parse(self):
        """Extract parse from HTML"""
        if self.title.text != "Sanskrit Reader Assistant":
            self.logger.error("Invalid output page.")
            return None

        word_nodes = self.soup.find_all("table", class_="yellow_back")
        roles = []
        for word_node in word_nodes:
            word_text = word_node.get_text().strip()
            word_row = word_node.find_parent("tr")
            tables = word_row.find_all("table")
            # analysis_table = tables[1]
            # word_id_table = tables[2]
            semantic_table = tables[3]
            semantic_rows = semantic_table.find_all("tr")
            word_roles = [row.get_text() for row in semantic_rows]
            roles.append({"text": word_text, "roles": word_roles})
        return roles

    def extract_declensions(self, headers: bool = True):
        """Extract declensions from HTML"""
        if self.title.text != "Sanskrit Grammarian Declension Engine":
            self.logger.error("Invalid output page.")
            return None
        table = self.soup.find("table", class_="inflexion")
        rows = table.find_all("tr")
        output = []
        for row in rows:
            cols = [col.get_text(" ").split() for col in row.find_all("th")]
            output.append(cols)
        output = output[:2] + output[3:] + [output[2]]
        if not headers:
            output = [row[1:] for row in output[1:]]
        return output

    def extract_conjugations(self, headers: bool = True):
        """Extract conjugations from HTML"""
        if self.title.text != "Sanskrit Grammarian Conjugation Engine":
            self.logger.error("Invalid output page.")
            return None
        tables = self.soup.find_all("table", class_="gris_cent")
        forms = {}
        for table in tables:
            header = table.find("span").get_text()
            forms[header] = {}
            inner_tables = table.find_all("table", class_="inflexion")

            for inner_table in inner_tables:
                rows = inner_table.find_all("tr")
                output = []
                for row in rows:
                    cols = [col.get_text(" ").split() for col in row.find_all("th")]
                    output.append(cols)
                forms[header][output[0][0][0]] = output

        return forms

    def extract_sandhi(self):
        """Extract Sandhi from HTML"""
        if self.title.text != "Sanskrit Sandhi Engine":
            self.logger.error("Invalid output page.")
            return None
        pattern = r"\s*([^\s\|]*)\s*\|\s*([^\s=]*)\s*=\s*([^\s]*)\s*"
        for span in self.body.find_all("span"):
            match = re.match(pattern, span.get_text(" "), flags=re.DOTALL)
            if match:
                return match.group(3)

            from bs4 import BeautifulSoup

    def parse_lexicon_entry(self, file_name, entry_tag):
        """
        Parses a Sanskrit Heritage lexicon entry from a BeautifulSoup tag.

        :param entry_tag: BeautifulSoup Tag object from get_lexicon_entry()
        :return: Dict containing structured lexicon data
        """
        if not entry_tag:
            return None

        # print("handling lexicon entry", entry_tag)

        # Extract headword in Devanagari
        headword = entry_tag.find("span", class_="Deva")
        headword = headword.text.strip() if headword else None

        # Extract transliterations (IAST)
        term_refs = []
        conj_forms = []
        alt_forms = {}
        for el in entry_tag.select("a.Blue"):
            blue = el.text.strip()

            red = None
            green = None

            for green_ in el.select("a.Green"):
                green = green_

            for red_ in el.select("a.Red"):
                red = red_

            if red:
                conj_forms.append(blue)
            elif green:
                # alt_forms.append(blue)
                term_refs.append(blue)
                ref_parts = green.get("href").split("#")
                green_page = None
                green_term = None
                remainder = []
                if len(ref_parts) == 1:
                    (t) = ref_parts
                    green_page = file_name
                    green_term = t
                elif len(ref_parts) == 2:
                    (p, t) = ref_parts
                    green_page = p
                    green_term = t
                else:
                    green_page = ref_parts[0]
                    green_term = ref_parts[1]
                    remainder = ref_parts[2:]
                    # raise ValueError(f"Unexpected ref: {blue}")
                if not green_page:
                    green_page = file_name
                alt_forms[blue] = tuple([green_page, green_term] + remainder)
                # print(green) # should be a map[blue] = (file, ref)
                # pass
                # pass
            else:
                term_refs.append(blue)

            # if blue.isdigit():
            # else:

        # these are all also blue...
        alternative_forms = (
            alt_forms  # [a.text.strip() for a in entry_tag.select("a.Green")]
        )

        # Extract grammatical category (gender, noun/verb, etc.)
        gender = None
        if entry_tag.find("a", class_="Red"):
            gender_text = entry_tag.find("a", class_="Red").text.strip()
            if "m." in gender_text:
                gender = "masculine"
            elif "n." in gender_text:
                gender = "neuter"
            elif "f." in gender_text:
                gender = "feminine"

        # Extract alternative forms (if any)

        # Extract the definition
        definition = " ".join(entry_tag.text.split()[1:])  # Skips the initial junk text

        return {
            "headword": headword,
            "reference_terms": term_refs,
            "conjugations": conj_forms,
            "gender": gender,
            "lexicon_terms": alternative_forms,
            "definition": definition,
        }

    def find_lexicon_entry(self, file_name, entry_id, variant=None):
        """
        Fetches a lexicon entry while checking alternative forms.
        """
        # First, try the direct lookup
        if "Monier-Williams Sanskrit-English" not in self.title.text:
            self.logger.error("Invalid dictionary page.")
            return None

        marker = self.soup.find("a", attrs={"name": entry_id})

        lexicon_entry = None

        if marker:
            lexicon_entry = marker.find_parent()

        if lexicon_entry:
            return lexicon_entry  # Found the entry

        # Debugging log if direct lookup fails
        # print(f"[DEBUG] Lexicon entry '{entry_id}' not found. Trying alternatives...")

        # Attempt alternative markers
        available_markers = [
            tag.get("name") for tag in self.soup.find_all(attrs={"name": True})
        ]

        # Try numbered variants (e.g., "H_raa#1", "H_raa#2")
        variant_part = "#"
        if variant:
            variant_part += variant
        numbered_variants = [
            m for m in available_markers if m.startswith(entry_id + variant_part)
        ]

        if len(numbered_variants):
            best_match = numbered_variants[0]  # Use first available match
            # print(f"[DEBUG] Using alternative lexicon marker: {best_match}")
            return self.find_lexicon_entry(file_name, best_match)

        raise ValueError(f"Lexicon entry for '{entry_id}' not found.")

    def extract_lexicon_entry(self, file_name: str, word_id: str, variant=None):
        """Extract entry from a lexicon"""
        parent = self.find_lexicon_entry(file_name, word_id, variant)
        # print("I found this parent do you like it?", parent)
        return self.parse_lexicon_entry(file_name, parent)

    @staticmethod
    def parse_reader_analysis(table: bs4.element.Tag):
        """
        Parse analysis of a single word
        Analysis Format is: [root]{analysis_1 | analysis_2 | ..}

        Parameters
        ----------
        table : bs4.element.Tag
            Valid `table` element

        Returns
        -------
        analysies : list
        """
        # pattern = r'\[([^\]]*)\]\{([^\}]*)\}'

        pattern = r"\[(.*?)\]\{([^\}]*)\}"
        rows = table.find_all("tr")
        analyses = []
        # print("time to analyze table", table)
        for row in rows:
            analysis = {}
            if row is None:
                analyses.append(analysis)
                continue

            link = row.find("a")
            # print("huh, I found this link?", link)
            # print("you may be interested in the row:", row)
            if link is not None:
                link_parts = link["href"].split("/")[-1].split("#")
                file_name, word_id = link_parts[0], link_parts[1]
            else:
                file_name, word_id = None, None

            match = re.match(pattern, row.get_text().strip(), flags=re.DOTALL)
            analysis["lexicon"] = (file_name, word_id)
            if match:
                analysis["root"] = match.group(1).split()[0].strip()
                analysis["analyses"] = [
                    [abbrev.replace(".", "") for abbrev in an.split()]
                    for an in match.group(2).split("|")
                ]
            analyses.append(analysis)
        return analyses

    def __repr__(self):
        return repr(self.soup)


###############################################################################


class HeritagePlatform:
    """
    The Sanskrit Heritage Platform

    Access various utilities from The Sanskrit Heritage Platform
    """

    INRIA_URL = "https://sanskrit.inria.fr/cgi-bin/SKT/"
    ACTIONS = {
        "reader": {"shell": "reader", "web": "sktgraph2.cgi"},
        "parser": {"shell": "parser", "web": "sktparser.cgi"},
        "search": {"shell": "indexer", "web": "sktindex.cgi"},
        "search_easy": {"shell": "indexerd", "web": "sktsearch.cgi"},
        "declension": {"shell": "declension", "web": "sktdeclin.cgi"},
        "conjugation": {"shell": "conjugation", "web": "sktconjug.cgi"},
        "lemma": {"shell": "lemmatizer", "web": "sktlemmatizer.cgi"},
        "sandhi": {"shell": "sandhier", "web": "sktsandhier.cgi"},
        "user": {"shell": "user_aid", "web": "sktuser.cgi"},
        "interface": {"shell": "interface", "web": "sktgraph.cgi"},
        "dictionary": {"shell": "../MW/", "web": "../../MW/"},
    }

    OPTIONS = {
        "lex": {
            "description": "Lexicon",
            "values": {
                "MW": "Monier-Williams Dictionary (English)",
                "SH": "Sanskrit Heritage Dictionary (French)",
            },
            "default": "MW",
        },
        "font": {
            "description": "Font for Sanskrit output",
            "values": {"deva": "Devanagari", "roma": "Roman (IAST)"},
            "default": "deva",
        },
        "t": {
            "description": "Internal Transliteration Scheme",
            "values": {"VH": "Velthuis"},
            "default": "VH",
        },
    }

    METHODS = ["shell", "web"]
    DEFAULT_METHOD = "shell"

    def __init__(
        self,
        base_dir: str = "",
        base_url: str = None,
        method: str = DEFAULT_METHOD,
        **kwargs,
    ):
        """
        Initialize Heritage Class

        Parameters
        ----------
        base_dir : str
            Path to the Heritage_Platform repository.
            The directory should contain 'ML' sub-directory,
            which further contains the scripts
        base_url : str, optional
            URL for the Heritage Platform Mirror.
            If None, the official INRIA website will be used.
            The default is None.
        method : str, optional
            Method used to obtain results. Results can be obtained either using
            the web installation or using UNIX shell.

            Possible values are, 'shell' and 'web'
            The default is 'shell'.
        """
        self.logger = logging.getLogger(__name__)
        self.base_url = self.INRIA_URL if base_url is None else base_url
        self.base_dir = base_dir
        self.scripts_dir = os.path.join(self.base_dir, "ML")

        self.method = None
        self.set_method(method)

        if not self.valid_installation():
            self.logger.warning("Heritage Platform installation not found.")
            self.base_dir = ""
            self.scripts_dir = ""
            self.set_method("web")

        self.options = {}
        for option in self.OPTIONS:
            self.options[option] = self.OPTIONS[option]["default"]

        self.web_url_cache = {}

    ###########################################################################
    # Utilities (Actions)

    def get_analysis(
        self,
        input_text: str,
        sentence: bool = True,
        unsandhied: bool = False,
        meta: bool = False,
    ):
        """
        Obtain morphological analyses using The Sanskrit Reader Companion

        Parameters
        ----------
        input_text : str
            Input text to analyse
        sentence : bool, optional
            The input is treated as a sentence, if true, otherwise as a word.
            The default is True.
        unsandhied : bool, optional
            If True, the input text is assumed to not contain sandhi.
            The default is False.
        meta : bool, optional
            The option is passed to HeritageOutput.extract_analysis().
            The default is False.

        Returns
        -------
        dict
            Dictionary of valid morphological analyses with solution_id as keys
        """

        opt_st = "t" if sentence else "f"
        opt_us = "t" if unsandhied else "f"

        options = {
            "lex": self.get_lexicon(),
            # "cache": "t",  # Use Cache (t)rue, (f)alse
            "st": opt_st,  # Sentence (t)rue, Word (f)alse
            "us": opt_us,  # Unsandhied (t)rue, (f)alse
            # if 'us' is 'f', "ca eva" is parsed as "ca_eva",
            # "tathā eva" as "tathā_eva" etc.
            "t": self.get_option("t"),
            # Tagging does not prune any solutions
            "font": self.get_font(),
            # Output Display Font (deva)nagari (roma)n
            "topic": "",
            "corpmode": "",
            "corpdir": "",
            "sentno": "980",  # what is this?
            "text": self.prepare_input(input_text),
        }

        if self.method == "shell":
            options["cp"] = "t"  # Full Parser Strength (t)rue, (f)alse
            options["mode"] = "p"  # Parse Mode (p)arsing, (t)agging
        else:
            options["mode"] = "f"

        result = self.get_result("reader", options)
        if result is None:
            return None

        output = HeritageOutput(result)
        # return output
        return output.extract_analysis(meta=meta)

    def hydrate_sentence(self, analysis_result):
        """
        Expands a sentence analysis by adding full lexicon data.
        """
        cache = TreeScopedCache(self)
        hydrated_result = {}

        for token_id, token_data in analysis_result.items():
            expanded_words = []
            for word_group in token_data["words"]:
                enriched_words = []
                for word in word_group:
                    lexicon = word.get("lexicon", None)
                    # print("getting da word", lexicon)

                    # Fetch lexicon data for this word
                    lexicon_entry = None
                    if lexicon:
                        lexicon_entry = cache.get_lexicon_entry(*lexicon)

                    # Merge lexicon data into the word structure
                    enriched_word = {
                        "text": word["text"],
                        "root": word["root"],
                        "category": word["category"],
                        "lexicon": lexicon_entry,  # Inject full lexicon meaning
                        "analyses": word["analyses"],
                    }
                    enriched_words.append(enriched_word)

                expanded_words.append(enriched_words)

            hydrated_result[token_id] = {"id": token_id, "words": expanded_words}

        return hydrated_result

    # ----------------------------------------------------------------------- #

    def get_parse(
        self,
        input_text: str,
        solution_id: int = None,
        sentence: bool = True,
        unsandhied: bool = False,
    ):
        """
        Obtain parse of a sentence using The Sanskrit Reader Companion

        Parameters
        ----------
        input_text : str
            Input text to analyse
        solution_id : int, optional
            Solution ID to parse.
            If None, the first solution ID is used.
            The default is None.
        sentence : bool, optional
            The input is treated as a sentence, if true, otherwise as a word.
            The option is passed to HeritagePlatform.get_analysis().
            The default is True.
        unsandhied : bool, optional
            If True, the input text is assumed to not contain sandhi.
            The option is passed to HeritagePlatform.get_analysis().
            The default is False.

        Returns
        -------
        dict
            Parse of the sentence
        """
        solutions = self.get_analysis(
            input_text, sentence=sentence, unsandhied=unsandhied, meta=True
        )

        # If solution ID not provided, use the first solution
        if solution_id is None:
            if not solutions:
                return None  # TODO: Change this to something ?

            solution_id = next(iter(solutions))

        # No need to manually give options again, since it does it for us
        # Internally parser is a re-run of reader until a specific solution
        # Remove following block in later versions

        # opt_st = 't' if sentence else 'f'
        # opt_us = 't' if unsandhied else 'f'

        # options = {
        #     'lex': self.get_lexicon(),
        #     'cache': 't',  # Use Cache (t)rue, (f)alse
        #     'st': opt_st,  # Sentence (t)rue, Word (f)alse
        #     'us': opt_us,  # Unsandhied (t)rue, (f)alse
        #                    # if 'us' is 'f', "ca eva" is parsed as "ca_eva",
        #                    # "tathā eva" as "tathā_eva" etc.
        #     'cp': 't',     # Full Parser Strength (t)rue, (f)alse
        #     't': self.get_option('t'),
        #     'mode': 'p',   # Parse Mode (p)arse, (g)raph, (s)ummary
        #     'font': self.get_font(),
        #                    # Output Display Font (deva)nagari (roma)n
        #     'topic': '',
        #     'n': solution_id,
        #     'abs': 'f',     # TODO: Find out what this does
        #     'text': self.prepare_input(input_text)
        # }

        solution = solutions[solution_id]
        options = solution["parser_options"]
        result = self.get_result("parser", options)
        output = HeritageOutput(result)
        roles = output.extract_parse()
        solution["roles"] = roles

        return solution

    # ----------------------------------------------------------------------- #

    def sandhi(self, word_1: str, word_2: str, mode: str = "internal"):
        """
        Join two words by forming a Sandhi

        Parameters
        ----------
        word_1 : str
            The first (left) word in the Sandhi
        word_2 : str
            The second (right) word in the Sandhi
        mode : str, optional
            Indicates whether the words join to form a single word or not
            Possible values are,
            * internal
            * external
            The default is 'internal'.

        Returns
        -------
        sandhi : str
            String obtained by forming the Sandhi
        """
        if mode not in ["internal", "external"]:
            self.logger.warning(f"Invalid mode: '{mode}'")

        options = {
            "lex": self.get_lexicon(),
            "l": self.prepare_input(word_1),
            "r": self.prepare_input(word_2),
            "t": self.get_option("t"),
            "k": mode,
            "font": self.get_font(),
        }
        result = self.get_result("sandhi", options)
        output = HeritageOutput(result)

        return output.extract_sandhi()

    # ----------------------------------------------------------------------- #

    def search_inflected_form(self, word: str, category: str):
        """
        Search an inflected form

        Parameters
        ----------
        word : str
            Sanskrit Word to search (in Devanagari)
        category : str
            Type of the word
                * Noun: Noun
                * Pron: Pronoun
                * Part: Participle
                * Inde: Indeclinible
                * Absya, Abstvaa, Voca, Iic, Ifc, Iiv, Piic etc.
        Returns
        -------
        matches : list
            List of matches.
        """
        options = {
            "t": self.get_option("t"),
            "q": self.prepare_input(word),
            "c": category,
            "font": self.get_font(),
        }
        result = self.get_result("lemma", options)
        output = HeritageOutput(result)

        # TODO: Output Parsing
        return output

    # ----------------------------------------------------------------------- #

    def get_declensions(
        self, word: str, gender: str, headers: bool = True, lexicon: str = None
    ):
        options = {
            "lex": self.get_lexicon(),
            "t": self.get_option("t"),
            "q": self.prepare_input(word),
            "g": self.identify_gender(gender),
            "font": self.get_font(),
        }
        result = self.get_result("declension", options)
        output = HeritageOutput(result)

        return output.extract_declensions(headers=headers)

    # ----------------------------------------------------------------------- #

    def get_conjugations(self, word: str, gana: str, lexicon: str = None):
        options = {
            "lex": self.get_lexicon(),
            "t": self.get_option("t"),
            "q": self.prepare_input(word),
            "c": gana,
            "font": self.get_font(),
        }
        result = self.get_result("conjugation", options)
        output = HeritageOutput(result)

        # TODO: Output Parsing
        return output

    # ----------------------------------------------------------------------- #

    def search_lexicon(self, word: str, lexicon: str = None):
        """Search a word in the dictionary

        Parameters
        ----------
        word : str
            Sanskrit Word to search (in Devanagari)
        lexicon : str, optional
            Lexicon to search the word in.
            Possible values are,

              - MW: Monier-Williams Dictionary
              - SH: Heritage Dictionary

            The default is 'MW'.

        Returns
        -------
        matches : list
            List of matches.
        """
        options = {
            "lex": self.get_lexicon(),
            "t": self.get_option("t"),
            "q": self.prepare_input(word),
            "font": self.get_font(),
        }
        result = self.get_result("search", options)
        output = HeritageOutput(result)

        # TODO: Output Parsing
        # TODO: Currently not using the lexicon keyword argument
        # Is there any use for that argument? For this function?
        return output

    ###########################################################################

    def get_lexicon_entry(self, file_name: str, word_id: str, variant=None):
        if self.method == "shell":
            path = self.get_path("dictionary")
            file_path = os.path.join(path, file_name)
            with open(file_path, encoding="utf-8") as f:
                content = f.read()
        elif self.method == "web":
            url = self.get_url("dictionary")
            query_url = f"{url}{file_name}#{word_id}"
            content = self.__get(query_url)
        else:
            self.logger.error(f"Invalid method: '{self.method}'.")
            return

        # print("do you like content?", content)
        output = HeritageOutput(content)
        return output.extract_lexicon_entry(file_name, word_id, variant)

    ###########################################################################
    # Fetch Result through Web or Shell

    def get_result_from_web(self, url: str, options: dict, attempts: int = 3):
        """
        Get results from the Heritage Platform web mirror
        Exponential backoff is used in case there are network errors

        Parameters
        ----------
        url : str
            URL of the CGI script to call
            HeritagePlatform.get_url() can be used to generate supported URLs
        options : dict
            Dictionary containing valid options for the script
        attempts : int, optional
            Number of attempts for the exponential backoff
            The default is 3.

        Returns
        -------
        str
            Result (HTML) obtained
        """

        query_string = build_query_string(options)
        query_url = f"{url}?{query_string}"
        return self.__get(query_url, attempts=attempts)

    # @functools.cache
    def __get(self, query_url: str, attempts: int = 3):
        """
        Query web with exponential-backoff

        Parameters
        ----------
        query_url : str
            URL to query
        attempts : int, optional
            Number of attempts for the exponential backoff
            The default is 3.

        Returns
        -------
        str
            Result (HTML) obtained
        """
        query_url = query_url.split("#")[0]  # hash is not sent to server
        if query_url in self.web_url_cache:
            return self.web_url_cache[query_url]
        # print("IM INSIDE!!!", query_url, type(self))
        # query with exponential-backoff
        r = requests.get(query_url)
        if r.status_code != 200:
            for n in range(attempts):
                if n == 0:
                    self.logger.warning(f"URL: {query_url}")

                self.logger.warning(f"Status Code: {r.status_code} (n = {n})")

                fn = n
                backoff = (2**fn) + random.random()
                time.sleep(backoff)
                r = requests.get(query_url)

                if r.status_code == 200:
                    self.logger.info(f"Resolved! (n = {n})")
                    break
            else:
                self.logger.warning(f"Failed on '{query_url}' after {n} attempts.")
        r.encoding = r.apparent_encoding
        self.web_url_cache[query_url] = r.text
        return self.web_url_cache[query_url]

    # ----------------------------------------------------------------------- #

    def get_result_from_shell(self, path: str, options: dict, timeout: int = 30):
        """
        Get results from the Heritage Platform's local installation via shell

        Parameters
        ----------
        path : str
            Path to the executable script
            HeritagePlatform.get_path() can be used to generate supported paths
        options : dict
            Valid options for the script
        timeout : int, optional
            Timeout in seconds, after which the function will abort.
            The default is 30.

        Returns
        -------
        result : str
            Result (HTML) obtained
        """
        query_string = build_query_string(options)
        environment = frozendict({"QUERY_STRING": query_string})
        return self.__run(path, environment, timeout=timeout)

    def __run(self, path, environment: dict, timeout: int = 30):
        """
        Get results from shell through a subprocess call

        Parameters
        ----------
        path : str
            Path to the executable script
        environment : dict
            Environment variables to set
        timeout : int, optional
            Timeout in seconds, after which the function will abort.
            The default is 30.

        Returns
        -------
        result : str
            Result (HTML) obtained
        """
        alarm(timeout)
        result = None
        try:
            result_header = "Content-Type: text/html\n\n"
            # result = subprocess.check_output(path, env=environment).decode("utf-8")
            cmd = sh.Command(path)
            out = io.StringIO()
            with out:
                # print("Here is your cmd: ", cmd, environment)
                result = cmd(_out=out, _err=sys.stderr, _env=environment)
                # print("finished running yr cmd")
                result = out.getvalue()
                result = result[len(result_header) :]
                # print("Here is your result:", type(result))
        except TimeoutError:
            self.logger.error("TimeoutError")
            return None
        alarm(0)
        return result

    # ----------------------------------------------------------------------- #

    def get_result(self, action: str, options: dict, *args, **kwargs):
        """
        High-level function to obtain result for various actions

        Avoids the hassle of generating the URL or PATH.
        Utilizes the HeritagePlatform.method attribute to determine
        whether to fetch through shell or web.

        Parameters
        ----------
        action : str
            Action value corresponding to the utility to be used.
            Refer to HeritagePlatform.ACTIONS
        options : dict
            Valid options for the specified action

        Returns
        -------
        str
            Result (HTML) obtained
        """
        if self.method == "shell":
            path = self.get_path(action)
            return self.get_result_from_shell(path, options, *args, **kwargs)
        if self.method == "web":
            url = self.get_url(action)
            return self.get_result_from_web(url, options, *args, **kwargs)
        self.logger.error(f"Invalid method: '{self.method}'.")

    ###########################################################################

    def get_method(self):
        """Get the current method"""
        return self.method

    def set_method(self, method: str):
        """
        Set method for fetching the output

        Valid methods are listed in HeritagePlatform.METHODS
        """
        if method.lower() in self.METHODS:
            self.method = method.lower()
            return True
        self.logger.warning(f"Invalid method: '{method}'")
        if self.method is None:
            self.method = self.DEFAULT_METHOD
        return False

    # ----------------------------------------------------------------------- #

    def get_option(self, opt_name: str):
        """Get the value of global options"""
        if opt_name not in self.OPTIONS:
            self.logger.warning(f"Invalid option: '{opt_name}'")
            return None
        return self.options.get(opt_name, None)

    def set_option(self, opt_name: str, opt_value: str):
        """Set global options

        Any of these options, if expected by a particular utility from the
        Heritage Platform, will be directly used in the QUERY_STRING while
        fetching the output from that utility

        class variable OPTIONS stores the default values for options

        Each option contains,
        - a 'description' of the option
        - 'values' it can take (and descriptions of those values)
        - 'default' value

        """

        opt_name = opt_name.lower()
        if opt_name not in self.OPTIONS:
            self.logger.warning(f"Invalid option: '{opt_name}'")
            return False

        if opt_value in self.OPTIONS[opt_name]["values"]:
            self.options[opt_name] = opt_value
            return True

        self.logger.warning(f"Invalid value for option '{opt_name}': '{opt_value}'")
        return False

    # ----------------------------------------------------------------------- #

    def get_font(self):
        """Get current font for Sanskrit Output"""
        return self.get_option("font")

    def set_font(self, font: str):
        """Set font for Sanskrit output"""
        return self.set_option("font", font.lower())

    # ----------------------------------------------------------------------- #

    def get_lexicon(self):
        """Get current lexicon"""
        return self.get_option("lex")

    def set_lexicon(self, lexicon: str):
        """Set lexicon"""
        return self.set_option("lex", lexicon.upper())

    ###########################################################################
    # URL or Path Builders

    def get_url(self, action: str):
        """URL Builder"""
        return urllib.parse.urljoin(self.base_url, self.ACTIONS[action]["web"])

    def get_path(self, action: str):
        """Path Builder"""
        return os.path.join(self.scripts_dir, self.ACTIONS[action]["shell"])

    ###########################################################################

    def valid_installation(self):
        """Check if the Heritage Platform installation exists"""
        # TODO: A better check may be checking for the required executables
        # * If the file exists
        # * If the file is executable
        if self.method == "shell":
            return os.path.isdir(self.scripts_dir)
        else:
            # TODO: can validate http access
            return True

    ###########################################################################

    def __repr__(self):
        params = {
            "repository": self.base_dir,
            "url": self.base_url,
            "method": self.method,
        }
        repr_params = ", ".join([f'{k}="{v}"' for k, v in params.items()])
        return f"{self.__class__.__name__}({repr_params})"

    ###########################################################################
    # TODO: Move these to utils.py ??

    @staticmethod
    def prepare_input(input_text: str):
        """
        Prepare Input
            * Convert Devanagari to Velthuis
            * Join words by '+' instead of by whitespaces
        """
        return "+".join(devanagari_to_velthuis(input_text).split())

    @staticmethod
    def identify_gender(gender: str):
        genders = {
            "Mas": ["पु", "m"],
            "Fem": ["स्त्री", "f"],
            "Neu": ["नपु", "n"],
            "Any": ["*", "त्रि", "a"],
        }
        for gender_key, gender_list in genders.items():
            for g in gender_list:
                if gender.lower().startswith(g):
                    return gender_key


###############################################################################
